### ISSUE TITLE
upon reconfigure allow changing authoriation groups

### ISSUE THREAD

**Issue by gurvindersingh** [UNINETT/appstore#16]
Current reconfiguration allow changing flavor and version but not changing groups. We should support that as a user might want to allow more groups to access their application.

Also we can add to current warning on reconfiguration as "Locally stored data will be lost and running application will be killed when reconfiguring"

**Comment by paalka** [comment]
Closing, as 1be92257d10a58149c01bc4495c258037b6463f9 solves this
