### ISSUE TITLE
create cache for listing apps and status

### ISSUE THREAD

**Issue by gurvindersingh** [UNINETT/appstore#18]
as users only sees the namespace which he/she have access to. So having the status of this cached for configurable period (e.g. 30/60 secs) will elevate the load on api server and smooth user experience.

**Comment by paalka** [comment]
This is delayed till later, as the bottleneck seems to be TIller having to read all configmaps in order to determine which releases are part of a given namespace. Thus, if we fix this, tiller will return the releases significantly faster

**Comment by paalka** [comment]
This has now been somewhat improved, as our patched version of Helm now uses kubernetes labels to determine which releases are associated with a given namespace.

**Comment by gurvindersingh** [comment]
I think given the current status and future plan for helm, we can close this issue.
