### ISSUE TITLE
Make it possible to specify how many deleted apps to keep in a namespace

### ISSUE THREAD

**Issue by paalka** [UNINETT/appstore#20]
Currently all config maps related to deleted applications are kept, we only want to keep some of these

**Comment by gurvindersingh** [comment]
We can go with 10 apps as default, I would say and have it a configurable options either via env vars or config file.

**Comment by paalka** [comment]
Closing, as 3a0ba6c17574ca333fe4a84f45f1644bbc3c9007 adds this.
