### ISSUE TITLE
when deleting app, delete its secret including tls cert

### ISSUE THREAD

**Issue by gurvindersingh** [UNINETT/appstore#22]
Currently it seems we are not deleting the ssl cert when deleting the app. We should delete it unless it is wildcard cert. So check if the secret name is `wildcard-tls` then leave it otherwise delete it with the deletion of app. As now we have hit the default resource limit on secret in scratch namespace.

**Comment by paalka** [comment]
Ingress specific TLS secrets should from 6058abf36efdc7cc7348db6add4cba6628e61b1e be deleted
