### ISSUE TITLE
Ensure that quotas using different units are parsed correctly

### ISSUE THREAD

**Issue by paalka** [Uninett/appstore#26]
Currently, quotas using Gi are parsed incorrectly.

**Comment by paalka** [comment]
Units are parsed correctly, it just the frontend that always presents the resources in decimal SI format. So, if a quota uses binary SI, the frontend will present it in the wrong format. This is however somewhat difficult to improve, as we either will have to convert to different formats in the frontend, which may confuse the user, as we suddenly use two different units. Otherwise, the some of the quotas will just be somewhat weird (as in having non-round numbers), which is IMO less confusing but is uglier.

**Comment by gurvindersingh** [comment]
we will stick with G only. Add this to documentation.

**Comment by paalka** [comment]
This has now been added.
