### ISSUE TITLE
investigate caching of resources

### ISSUE THREAD

**Issue by gurvindersingh** [UNINETT/appstore#9]
Currently it seems we poll k8s api server for every user operation which is ok for development but once things get in prod we might have thousands of active user which amplify the load on api server. We should have a background thread which polls api server for all the resources every x secs and appstore backend use that cache to reply for all/most of the requests. This will enhance the user experience as well as scalability

**Comment by paalka** [comment]
This should now be improved.
Currently only resources that may change often (or depend on the JWT token) are re-fetched, such as information about deployments. Other resources should be cached for at least one minute
